- name: instalando o apache
  apt: name=apache2 state=present
  when: ansible_distribution == "Ubuntu"

- name: iniciando o apache2
  service: name=apache2 state=restarted
  when: ansible_distribution == "Ubuntu"
