---
- name: Desafio
  hosts: all
  tasks:
  - name: parando nginx
    service:
      name: nginx
      state: stopped
    ignore_errors: True

  - name: removendo nginx no ubuntu
    apt:
     name: nginx
     state: absent
    when: ansible_distribution == "Ubuntu"

  - name: removendo nginx no centos
    yum:
      name: nginx
      state: absent
    when: ansible_distribution == "CentOS"

  - name: instalando apache2
    apt:
     name: apache2
     state: present
    when: ansible_distribution == "Ubuntu"

  - name: instalando libapache2
    apt: 
     name: libapache2-mod-php7.0
     state: present 
    when: ansible_distribution == "Ubuntu"

  - name: instalando php7.0
    apt:
     name: php7.0
     state: present
    when: ansible_distribution == "Ubuntu"

  - name: instalando apache e php no centos
    yum:
     name: "{{ item }}"
     state: present
    with_items: [ httpd, php ]
    when: ansible_distribution == "CentoOS"

  - name: habilitando modulo php para apache
    command: a2enmod php7.0
    notify: restart apache2
    when: ansible_distribution == "Ubuntu"   

  - name: copiando um index.php
    copy:
     src: files/index.php
     dest: /var/www/html/

  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted

  - name: restart httpd
    service: 
      name: httpd
      state: restarted     
